//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cameo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cameo.Resources.ResourceTexts", typeof(ResourceTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все права защищены..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступность.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите стать доступным(ой)?.
        /// </summary>
        public static string AvailabilityConfirmationText {
            get {
                return ResourceManager.GetString("AvailabilityConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стать талантом.
        /// </summary>
        public static string BecomeTalent {
            get {
                return ResourceManager.GetString("BecomeTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История заказов.
        /// </summary>
        public static string BookingHistory {
            get {
                return ResourceManager.GetString("BookingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите отменить заказ?.
        /// </summary>
        public static string CancelOrderConfirmationText {
            get {
                return ResourceManager.GetString("CancelOrderConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить цену.
        /// </summary>
        public static string ChangePrize {
            get {
                return ResourceManager.GetString("ChangePrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код из смс.
        /// </summary>
        public static string CodeFromSMS {
            get {
                return ResourceManager.GetString("CodeFromSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не делать это видео публичным на Helloo.
        /// </summary>
        public static string DoNotMakeVideoPublic {
            get {
                return ResourceManager.GetString("DoNotMakeVideoPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить видео.
        /// </summary>
        public static string DownloadVideo {
            get {
                return ResourceManager.GetString("DownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать заказ.
        /// </summary>
        public static string EditOrder {
            get {
                return ResourceManager.GetString("EditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать фото.
        /// </summary>
        public static string EditPhoto {
            get {
                return ResourceManager.GetString("EditPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы скоро свяжемся с Вами..
        /// </summary>
        public static string EnrollCompleteBodyText {
            get {
                return ResourceManager.GetString("EnrollCompleteBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, что решили присоединиться к нам!.
        /// </summary>
        public static string EnrollCompleteHeaderText {
            get {
                return ResourceManager.GetString("EnrollCompleteHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас есть фанаты? Присоединяйтесь к нам как талант, чтобы быть с ними на связи!.
        /// </summary>
        public static string EnrollTip {
            get {
                return ResourceManager.GetString("EnrollTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to записей.
        /// </summary>
        public static string entries {
            get {
                return ResourceManager.GetString("entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код.
        /// </summary>
        public static string ErrorInvalidCode {
            get {
                return ResourceManager.GetString("ErrorInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный номер телефона.
        /// </summary>
        public static string ErrorInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка на сайте!.
        /// </summary>
        public static string ErrorOnSite {
            get {
                return ResourceManager.GetString("ErrorOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string ErrorRequiredField {
            get {
                return ResourceManager.GetString("ErrorRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить смс. Попробуйте позже..
        /// </summary>
        public static string ErrorUnableToSendSMS {
            get {
                return ResourceManager.GetString("ErrorUnableToSendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешается использоватьтолько строчные буквы и цифры.
        /// </summary>
        public static string ErrorUsernameValidationMessage {
            get {
                return ResourceManager.GetString("ErrorUsernameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество подписчиков (например: 400 тыс.).
        /// </summary>
        public static string FollowersCountDisplayName {
            get {
                return ResourceManager.GetString("FollowersCountDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное имя.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закажи персональное видео-обращение у своего кумира.
        /// </summary>
        public static string HomeHeaderText {
            get {
                return ResourceManager.GetString("HomeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкции.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно средств на балансе, чтобы заказать видео. Пожалуйста, пополните баланс..
        /// </summary>
        public static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние видео.
        /// </summary>
        public static string LatestVideos {
            get {
                return ResourceManager.GetString("LatestVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тест.
        /// </summary>
        public static string LogInTip {
            get {
                return ResourceManager.GetString("LogInTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти с помощью номера телефона.
        /// </summary>
        public static string LogInUsingPhoneNumber {
            get {
                return ResourceManager.GetString("LogInUsingPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите выйти?.
        /// </summary>
        public static string LogoutConfirmationText {
            get {
                return ResourceManager.GetString("LogoutConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление картой.
        /// </summary>
        public static string ManageCard {
            get {
                return ResourceManager.GetString("ManageCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string MyCategories {
            get {
                return ResourceManager.GetString("MyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои данные.
        /// </summary>
        public static string MyData {
            get {
                return ResourceManager.GetString("MyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество подписчиков.
        /// </summary>
        public static string MyNumberOfFollowers {
            get {
                return ResourceManager.GetString("MyNumberOfFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои проекты.
        /// </summary>
        public static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои проекты, категории.
        /// </summary>
        public static string MyProjectsCategories {
            get {
                return ResourceManager.GetString("MyProjectsCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меня можно найти в.
        /// </summary>
        public static string MySocialArea {
            get {
                return ResourceManager.GetString("MySocialArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моё имя пользователя в соц. сети.
        /// </summary>
        public static string MySocialAreaHandle {
            get {
                return ResourceManager.GetString("MySocialAreaHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок действия (мм/гг).
        /// </summary>
        public static string MyUzcardExpire {
            get {
                return ResourceManager.GetString("MyUzcardExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер Вашей карты Uzcard.
        /// </summary>
        public static string MyUzcardNumber {
            get {
                return ResourceManager.GetString("MyUzcardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена Вашего видео.
        /// </summary>
        public static string MyVideoPrice {
            get {
                return ResourceManager.GetString("MyVideoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичная оферта.
        /// </summary>
        public static string Oferta {
            get {
                return ResourceManager.GetString("Oferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали заказа.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ от.
        /// </summary>
        public static string OrderFrom {
            get {
                return ResourceManager.GetString("OrderFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость заказа.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость запроса.
        /// </summary>
        public static string OrderPrize {
            get {
                return ResourceManager.GetString("OrderPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось доплатить.
        /// </summary>
        public static string OrderRemainingPrize {
            get {
                return ResourceManager.GetString("OrderRemainingPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказов завершено.
        /// </summary>
        public static string OrdersCompleted {
            get {
                return ResourceManager.GetString("OrdersCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заработано.
        /// </summary>
        public static string OrdersEarned {
            get {
                return ResourceManager.GetString("OrdersEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выполненные.
        /// </summary>
        public static string OrdersNotCompleted {
            get {
                return ResourceManager.GetString("OrdersNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата подтверждена.
        /// </summary>
        public static string OrdersPaymentConfirmed {
            get {
                return ResourceManager.GetString("OrdersPaymentConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус заказа.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего заказов.
        /// </summary>
        public static string OrdersTotal {
            get {
                return ResourceManager.GetString("OrdersTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидается оплата.
        /// </summary>
        public static string OrdersWaitingForPayment {
            get {
                return ResourceManager.GetString("OrdersWaitingForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидают подтверждение оплаты.
        /// </summary>
        public static string OrdersWaitingForPaymentConfirmation {
            get {
                return ResourceManager.GetString("OrdersWaitingForPaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидают ответа.
        /// </summary>
        public static string OrdersWaitingForResponse {
            get {
                return ResourceManager.GetString("OrdersWaitingForResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидают видео.
        /// </summary>
        public static string OrdersWaitingForVideo {
            get {
                return ResourceManager.GetString("OrdersWaitingForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказать видео.
        /// </summary>
        public static string OrderVideo {
            get {
                return ResourceManager.GetString("OrderVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказать видео от.
        /// </summary>
        public static string OrderVideoFrom {
            get {
                return ResourceManager.GetString("OrderVideoFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный номер карты Вы можете использовать для перевода оставшейся суммы заказа.
        /// </summary>
        public static string PaymentScreenshotUploadText1 {
            get {
                return ResourceManager.GetString("PaymentScreenshotUploadText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как только выполните оплату, загрузите скрин, подтверждающий успешный перевод.
        /// </summary>
        public static string PaymentScreenshotUploadText2 {
            get {
                return ResourceManager.GetString("PaymentScreenshotUploadText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональные данные.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите, от кого.
        /// </summary>
        public static string ProvideFromWhom {
            get {
                return ResourceManager.GetString("ProvideFromWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похожие таланты.
        /// </summary>
        public static string RelatedTalents {
            get {
                return ResourceManager.GetString("RelatedTalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс.
        /// </summary>
        public static string ReplenishBalance {
            get {
                return ResourceManager.GetString("ReplenishBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить баланс на.
        /// </summary>
        public static string ReplenishBalanceOn {
            get {
                return ResourceManager.GetString("ReplenishBalanceOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск. Попробуйте &apos;Abduvali&apos; или &apos;Абдували&apos;.
        /// </summary>
        public static string SearchInputPlaceholder {
            get {
                return ResourceManager.GetString("SearchInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показано.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смс.
        /// </summary>
        public static string Sms {
            get {
                return ResourceManager.GetString("Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где можно Вас найти?.
        /// </summary>
        public static string SocialAreaDisplayName {
            get {
                return ResourceManager.GetString("SocialAreaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше имя в соц.сети (например: petrivanov).
        /// </summary>
        public static string SocialAreaHandleDisplayName {
            get {
                return ResourceManager.GetString("SocialAreaHandleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные успешно сохранены.
        /// </summary>
        public static string SuccessDataSaved {
            get {
                return ResourceManager.GetString("SuccessDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ успешно сформирован!.
        /// </summary>
        public static string SuccessOrderCreated {
            get {
                return ResourceManager.GetString("SuccessOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ успешно отредактирован!.
        /// </summary>
        public static string SuccessOrderEdited {
            get {
                return ResourceManager.GetString("SuccessOrderEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таланты не могут заказывать видео. Зайдите как клиент..
        /// </summary>
        public static string TalentsCannotOrder {
            get {
                return ResourceManager.GetString("TalentsCannotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя таланта.
        /// </summary>
        public static string TalentsName {
            get {
                return ResourceManager.GetString("TalentsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила пользования.
        /// </summary>
        public static string TermsOfUsage {
            get {
                return ResourceManager.GetString("TermsOfUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для.
        /// </summary>
        public static string ToBig {
            get {
                return ResourceManager.GetString("ToBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите стать недоступным(ой)?.
        /// </summary>
        public static string UnavailabilityConfirmationText {
            get {
                return ResourceManager.GetString("UnavailabilityConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить заказ.
        /// </summary>
        public static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить другой скрин.
        /// </summary>
        public static string UploadAnotherScreenshot {
            get {
                return ResourceManager.GetString("UploadAnotherScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить скрин.
        /// </summary>
        public static string UploadScreenshot {
            get {
                return ResourceManager.GetString("UploadScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сум.
        /// </summary>
        public static string UZS {
            get {
                return ResourceManager.GetString("UZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео скрыто от других.
        /// </summary>
        public static string VideoIsHidden {
            get {
                return ResourceManager.GetString("VideoIsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше видео готово!.
        /// </summary>
        public static string VideoIsReady {
            get {
                return ResourceManager.GetString("VideoIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео заказано от.
        /// </summary>
        public static string VideoOrderedFrom {
            get {
                return ResourceManager.GetString("VideoOrderedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео для.
        /// </summary>
        public static string VideoTo {
            get {
                return ResourceManager.GetString("VideoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это видео:.
        /// </summary>
        public static string VideoType {
            get {
                return ResourceManager.GetString("VideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смотреть.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите стать талантом на Helloo?.
        /// </summary>
        public static string WishToBecomeTalent {
            get {
                return ResourceManager.GetString("WishToBecomeTalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш баланс.
        /// </summary>
        public static string YourBalance {
            get {
                return ResourceManager.GetString("YourBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы отсутствуют.
        /// </summary>
        public static string ZeroRecords {
            get {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
